const { SlashCommandBuilder } = require('discord.js');

const hiddenCommandAliases = new Set([
    'live-exception',
    'assign-roles',
    'report-regular',
    'report-analysis',
    'ranking',
    'refresh',
    'sync-working',
    'permission-check',
    'data-audit',
    'inactive-candidates',
    'status-audit',
    'time-audit',
    'dayoff-log',
    'dayoff-list',
    'dayoff-approve',
    'dayoff-cancel',
    'dayoff-cancel-force',
    'dayoff-reject',
    '강제조기퇴근',
    'force-in',
    'force-out',
    'force-early-out',
    'force-off',
    'force-ot',
    'reset-all',
    'my-info',
    'diagnostics',
    'backup-create',
    'backup-list',
    'backup-restore',
    'set-announce',
    'cancel-announce',
    'list-announce',
    'fire',
    'clear-roles',
    'manual-adjust'
]);

function buildCommandDefinitions() {
    return [
        new SlashCommandBuilder().setName('라이브예외').setDescription('Approve live exception').addUserOption(o=>o.setName('대상').setRequired(true).setDescription('Target')).addStringOption(o=>o.setName('사유').setRequired(true).setDescription('Reason')).addIntegerOption(o=>o.setName('시간').setDescription('Hours; leave blank to use shift end').setMinValue(1).setMaxValue(12)),
        new SlashCommandBuilder().setName('live-exception').setDescription('Approve live exception').addUserOption(o=>o.setName('target').setRequired(true).setDescription('Target')).addStringOption(o=>o.setName('reason').setRequired(true).setDescription('Reason')).addIntegerOption(o=>o.setName('hours').setDescription('Hours; leave blank to use shift end').setMinValue(1).setMaxValue(12)),
        new SlashCommandBuilder().setName('역할').setDescription('Assign roles').addUserOption(o=>o.setName('대상').setRequired(true).setDescription('Target')).addStringOption(o=>o.setName('서버').setRequired(true).setDescription('Server').addChoices({name:'Heine',value:'HEINE'},{name:'Paagrio',value:'PAAGRIO'})).addStringOption(o=>o.setName('시프트').setRequired(true).setDescription('Shift').addChoices({name:'Day',value:'DAY'},{name:'Night',value:'NIGHT'})),
        new SlashCommandBuilder().setName('assign-roles').setDescription('Assign roles').addUserOption(o=>o.setName('target').setRequired(true).setDescription('Target')).addStringOption(o=>o.setName('server').setRequired(true).setDescription('Server').addChoices({name:'Heine',value:'HEINE'},{name:'Paagrio',value:'PAAGRIO'})).addStringOption(o=>o.setName('shift').setRequired(true).setDescription('Shift').addChoices({name:'Day',value:'DAY'},{name:'Night',value:'NIGHT'})),
        new SlashCommandBuilder().setName('일반보고').setDescription('Summary report'), new SlashCommandBuilder().setName('report-regular').setDescription('Summary report'),
        new SlashCommandBuilder().setName('정밀보고').setDescription('Deep report'), new SlashCommandBuilder().setName('report-analysis').setDescription('Deep report'),
        new SlashCommandBuilder().setName('랭킹').setDescription('Ranking'), new SlashCommandBuilder().setName('ranking').setDescription('Ranking'),
        new SlashCommandBuilder().setName('현황판갱신').setDescription('Refresh'), new SlashCommandBuilder().setName('refresh').setDescription('Refresh'),
        new SlashCommandBuilder().setName('워킹동기화').setDescription('Sync WORKING roles'), new SlashCommandBuilder().setName('sync-working').setDescription('Sync WORKING roles'),
        new SlashCommandBuilder().setName('권한진단').setDescription('Permission check'), new SlashCommandBuilder().setName('permission-check').setDescription('Permission check'),
        new SlashCommandBuilder().setName('데이터검사').setDescription('Data audit'), new SlashCommandBuilder().setName('data-audit').setDescription('Data audit'),
        new SlashCommandBuilder().setName('비활동검사').setDescription('Inactive kick candidate report').addIntegerOption(o=>o.setName('일수').setDescription('Inactive days').setMinValue(1).setMaxValue(30)),
        new SlashCommandBuilder().setName('inactive-candidates').setDescription('Inactive kick candidate report').addIntegerOption(o=>o.setName('days').setDescription('Inactive days').setMinValue(1).setMaxValue(30)),
        new SlashCommandBuilder().setName('상태검사').setDescription('Recorded status audit'), new SlashCommandBuilder().setName('status-audit').setDescription('Recorded status audit'),
        new SlashCommandBuilder().setName('시간검사').setDescription('Time logic audit'), new SlashCommandBuilder().setName('time-audit').setDescription('Time logic audit'),
        new SlashCommandBuilder().setName('휴무로그').setDescription('Day off audit log').addIntegerOption(o=>o.setName('갯수').setDescription('Limit').setMinValue(1).setMaxValue(30)),
        new SlashCommandBuilder().setName('dayoff-log').setDescription('Day off audit log').addIntegerOption(o=>o.setName('limit').setDescription('Limit').setMinValue(1).setMaxValue(30)),
        new SlashCommandBuilder().setName('휴무목록').setDescription('Day off list').addStringOption(o=>o.setName('상태').setDescription('Status').addChoices({name:'All',value:'all'},{name:'Pending',value:'pending'},{name:'Approved',value:'approved'},{name:'Today',value:'today'},{name:'Worked',value:'worked'},{name:'Cancelled',value:'cancelled'},{name:'Rejected',value:'rejected'})),
        new SlashCommandBuilder().setName('dayoff-list').setDescription('Day off list').addStringOption(o=>o.setName('status').setDescription('Status').addChoices({name:'All',value:'all'},{name:'Pending',value:'pending'},{name:'Approved',value:'approved'},{name:'Today',value:'today'},{name:'Worked',value:'worked'},{name:'Cancelled',value:'cancelled'},{name:'Rejected',value:'rejected'})),
        new SlashCommandBuilder().setName('휴무승인').setDescription('Approve day off').addUserOption(o=>o.setName('대상').setRequired(true).setDescription('Target')).addStringOption(o=>o.setName('날짜').setRequired(true).setDescription('Date')),
        new SlashCommandBuilder().setName('dayoff-approve').setDescription('Approve day off').addUserOption(o=>o.setName('target').setRequired(true).setDescription('Target')).addStringOption(o=>o.setName('date').setRequired(true).setDescription('Date')),
        new SlashCommandBuilder().setName('휴무취소').setDescription('Cancel day off').addUserOption(o=>o.setName('대상').setRequired(true).setDescription('Target')).addStringOption(o=>o.setName('날짜').setRequired(true).setDescription('Date')),
        new SlashCommandBuilder().setName('dayoff-cancel').setDescription('Cancel day off').addUserOption(o=>o.setName('target').setRequired(true).setDescription('Target')).addStringOption(o=>o.setName('date').setRequired(true).setDescription('Date')),
        new SlashCommandBuilder().setName('강제휴무취소').setDescription('Cancel exactly one day off without date').addUserOption(o=>o.setName('대상').setRequired(true).setDescription('Target')),
        new SlashCommandBuilder().setName('dayoff-cancel-force').setDescription('Cancel exactly one day off without date').addUserOption(o=>o.setName('target').setRequired(true).setDescription('Target')),
        new SlashCommandBuilder().setName('휴무반려').setDescription('Reject day off').addUserOption(o=>o.setName('대상').setRequired(true).setDescription('Target')).addStringOption(o=>o.setName('날짜').setRequired(true).setDescription('Date')).addStringOption(o=>o.setName('사유').setDescription('Reason')),
        new SlashCommandBuilder().setName('dayoff-reject').setDescription('Reject day off').addUserOption(o=>o.setName('target').setRequired(true).setDescription('Target')).addStringOption(o=>o.setName('date').setRequired(true).setDescription('Date')).addStringOption(o=>o.setName('reason').setDescription('Reason')),
        new SlashCommandBuilder().setName('강제출근').setDescription('Force in').addUserOption(o=>o.setName('대상').setRequired(true).setDescription('Target')),
        new SlashCommandBuilder().setName('강제퇴근').setDescription('Force out').addUserOption(o=>o.setName('대상').setRequired(true).setDescription('Target')),
        new SlashCommandBuilder().setName('강제휴무').setDescription('Force off').addUserOption(o=>o.setName('대상').setRequired(true).setDescription('Target')),
        new SlashCommandBuilder().setName('강제연장').setDescription('Force OT').addUserOption(o=>o.setName('대상').setRequired(true).setDescription('Target')),
        new SlashCommandBuilder().setName('리셋').setDescription('Reset one user').addUserOption(o=>o.setName('대상').setRequired(true).setDescription('Target')),
        new SlashCommandBuilder().setName('전체리셋').setDescription('Reset all attendance data'), new SlashCommandBuilder().setName('reset-all').setDescription('Reset all attendance data'),
        new SlashCommandBuilder().setName('내정보').setDescription('My info'), new SlashCommandBuilder().setName('my-info').setDescription('My info'),
        new SlashCommandBuilder().setName('진단').setDescription('Diagnostics'), new SlashCommandBuilder().setName('diagnostics').setDescription('Diagnostics'),
        new SlashCommandBuilder().setName('백업생성').setDescription('Backup create'), new SlashCommandBuilder().setName('backup-create').setDescription('Backup create'),
        new SlashCommandBuilder().setName('백업목록').setDescription('Backup list'), new SlashCommandBuilder().setName('backup-list').setDescription('Backup list'),
        new SlashCommandBuilder().setName('백업복구').setDescription('Backup restore').addStringOption(o=>o.setName('파일').setDescription('File')), new SlashCommandBuilder().setName('backup-restore').setDescription('Backup restore').addStringOption(o=>o.setName('file').setDescription('File')),
        new SlashCommandBuilder().setName('공지설정').setDescription('Set announce').addIntegerOption(o=>o.setName('번호').setRequired(true).setMinValue(1).setMaxValue(6).setDescription('Slot')).addRoleOption(o=>o.setName('대상').setRequired(true).setDescription('Target')).addStringOption(o=>o.setName('시간').setRequired(true).setDescription('HH:mm')).addStringOption(o=>o.setName('내용').setRequired(true).setDescription('Content')),
        new SlashCommandBuilder().setName('set-announce').setDescription('Set announce').addIntegerOption(o=>o.setName('slot').setRequired(true).setMinValue(1).setMaxValue(6).setDescription('Slot')).addRoleOption(o=>o.setName('target').setRequired(true).setDescription('Target')).addStringOption(o=>o.setName('time').setRequired(true).setDescription('HH:mm')).addStringOption(o=>o.setName('content').setRequired(true).setDescription('Content')),
        new SlashCommandBuilder().setName('공지취소').setDescription('Cancel announce').addIntegerOption(o=>o.setName('번호').setRequired(true).setMinValue(1).setMaxValue(6).setDescription('Slot')), new SlashCommandBuilder().setName('cancel-announce').setDescription('Cancel announce').addIntegerOption(o=>o.setName('slot').setRequired(true).setMinValue(1).setMaxValue(6).setDescription('Slot')),
        new SlashCommandBuilder().setName('공지목록').setDescription('List announce'), new SlashCommandBuilder().setName('list-announce').setDescription('List announce'),
        new SlashCommandBuilder().setName('해고').setDescription('Kick').addUserOption(o=>o.setName('대상').setRequired(true).setDescription('Target')), new SlashCommandBuilder().setName('fire').setDescription('Kick').addUserOption(o=>o.setName('target').setRequired(true).setDescription('Target')),
        new SlashCommandBuilder().setName('역할삭제').setDescription('Clear roles').addUserOption(o=>o.setName('대상').setRequired(true).setDescription('Target')), new SlashCommandBuilder().setName('clear-roles').setDescription('Clear roles').addUserOption(o=>o.setName('target').setRequired(true).setDescription('Target')),
        new SlashCommandBuilder().setName('수동수정').setDescription('Manual adjust').addUserOption(o=>o.setName('대상').setRequired(true).setDescription('Target')).addStringOption(o=>o.setName('항목').setRequired(true).setDescription('Field').addChoices({name:'points',value:'points'},{name:'status',value:'status'},{name:'shift',value:'shift'},{name:'checked-in',value:'checked-in'},{name:'day-off',value:'day-off'},{name:'disconnected',value:'disconnected'},{name:'finished',value:'finished'},{name:'normal',value:'normal'},{name:'late',value:'late'},{name:'absent',value:'absent'},{name:'early',value:'early'},{name:'ot',value:'ot'},{name:'off',value:'off'},{name:'dc',value:'dc'},{name:'strikes',value:'strikes'})).addStringOption(o=>o.setName('값').setRequired(true).setDescription('Value')),
        new SlashCommandBuilder().setName('manual-adjust').setDescription('Manual adjust').addUserOption(o=>o.setName('target').setRequired(true).setDescription('Target')).addStringOption(o=>o.setName('field').setRequired(true).setDescription('Field').addChoices({name:'points',value:'points'},{name:'status',value:'status'},{name:'shift',value:'shift'},{name:'checked-in',value:'checked-in'},{name:'day-off',value:'day-off'},{name:'disconnected',value:'disconnected'},{name:'finished',value:'finished'},{name:'normal',value:'normal'},{name:'late',value:'late'},{name:'absent',value:'absent'},{name:'early',value:'early'},{name:'ot',value:'ot'},{name:'off',value:'off'},{name:'dc',value:'dc'},{name:'strikes',value:'strikes'})).addStringOption(o=>o.setName('value').setRequired(true).setDescription('Value'))
    ];
}

module.exports = {
    buildCommandDefinitions,
    hiddenCommandAliases
};
